#!/bin/sh
#
# Start modules
#

MODULES="snd_bcm2835
p54usb"

start() {
	printf "Starting modules: "
	for i in $MODULES ; do echo $i && modprobe $i ; done
	echo "OK"
}

stop() {
	printf "Stopping modules: "
	for i in $MODULES ; do echo $i && modprobe -r $i ; done
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
