#!/bin/sh
#
# Setup directory layout
#

DIRECTORIES="
/var/empty
/var/lib/alsa
/var/lib/mpd
/var/lib/dhcp
/var/lib/misc
/var/www
/var/cache
/var/lock
/var/log
/var/spool
/var/tmp
"

start() {
        printf "Setting up directories: "
        mkdir -p $DIRECTORIES
        ln -s /run /var/run
        echo "OK"
}

stop() {
        printf "Setting up directories: "
        echo "OK"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
