#!/bin/sh
#
# Start eth0 dhclient in background
#

start() {
	printf "Starting dhcp client for eth0: "
	nohup dhclient eth0 2>&1 >> /var/log/dhclient-eth0.log  &
	echo "OK"
}

stop() {
	printf "Stopping dhcp client for eth0: "
	kill -15 $(ps -o pid,args | grep 'dhclient eth0' | grep -v grep | sed 's/^ *//g'| cut -d' ' -f1)
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
