#!/bin/sh
#
# Start ympd web ui
#

start() {
	printf "Starting MPD web ui: "
	nohup ympd 2>&1 >> /var/log/ympd.log  &
	echo "OK"
}

stop() {
	printf "Stopping MPD web ui: "
	kill -15 $(ps -o pid,args | grep 'ympd' | grep -v grep | sed 's/^ *//g'| cut -d' ' -f1)
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
